apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim  # name of PVC essential for identifying the storage data
  namespace: ninja 
  labels:
    app: mongodb
    # tier: database
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    #This will tell kubernetes about the amount of space we are trying to claim.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: ninja
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        volumeMounts:        # Mounting voulume obtained from Persistent Volume Claim
            - name: mongodb-persistent-storage
              mountPath: /data/db #This is the path in the container on which the mounting will take place.
      volumes:
        - name: mongodb-persistent-storage # Obtaining 'vloume' from PVC
          persistentVolumeClaim:
            claimName: mongodb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: ninja
spec:
  selector:
    app: mongodb
  ports: 
      - 
        name: "mongodb"
        port: 27017
        nodePort: 30332
  type: "NodePort"